
server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/Bottle_Coffin/Desktop/git-local-repo
          uri: https://github.com/leebyeounggwan/spring-cloud-config.git
          default-label: main
#         private repository인 경우
#         username: [username]
#         password: [password]

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh
